version: '1'
services:
  app:
    container_name: node-03
    volumes:
      - .:/app
    restart: always
    build: .
    ports:
      - '2000:2000'
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    restart: always 
    ports:
      - '27017:27017'